Some changes
normalized app name, skip next update if abusing, add $NOTH var (if set to 1, it doesn't print the 'nothing to update' message. set to 0 to print)

diff --git a/dnsomatic b/dnsomatic
--- a/dnsomatic
+++ b/dnsomatic
@@ -4,6 +4,7 @@
 #shellcheck source=/dev/null
 #DNS-O-MATIC updater by maghuro 2020
 APPNAME="DNSOMatic"
+APPNAMEnorm="$(echo $APPNAME | tr 'A-Z' 'a-z')"
 CFG="/jffs/addons/$(echo $APPNAME | tr 'A-Z' 'a-z').d/settings.cfg"
 readonly CRIT="\\e[41m"
 readonly ERR="\\e[31m"
@@ -12,7 +13,7 @@ readonly PASS="\\e[32m"
 
 #set -x
 
-[ ! -f "/opt/bin/$(echo $APPNAME | tr 'A-Z' 'a-z')" ] && ln -s "$0" "/opt/bin/$(echo $APPNAME | tr 'A-Z' 'a-z')" >/dev/null 2>&1
+[ -f "/opt/bin/$APPNAMEnorm" ] || ln -s "$0" "/opt/bin/$APPNAMEnorm" >/dev/null 2>&1
  
 if [ ! -f "$CFG" ]; then
    printf "" > "$CFG"
@@ -40,7 +41,7 @@ fi
 if [ "$1" = "set" ]; then
     if [ -n "$2" ] && [ -n "$3" ]; then
        setvar "$2" "$3"
-       Print_Output "Setting $(echo "$2" | tr -d " ")=$(echo "$3" | tr -d " ")..."
+       Print_Output "Setting \"$(echo "$2" | tr -d " ")=$(echo "$3" | tr -d " ")\"..."
        exit 0
     else
        echo "Missing args"
@@ -48,16 +49,22 @@ if [ "$1" = "set" ]; then
     fi
 fi
 
+if [ "$ABUSE" = "1" ]; then
+   setvar ABUSE 0
+   Print_Output "Last update was abusive, skipping this one..."
+   exit 0
+fi
+
 missing=0
 for vars in USERNAME PASSWORD HOSTNAME; do
     if ! grep -q "$vars=" < "$CFG"; then
        missing=1
-       Print_Output "Please use \"$(echo $APPNAME | tr 'A-Z' 'a-z') set $vars VALUE\" before first run" "$CRIT"
+       Print_Output "Please use \"$APPNAMEnorm set $vars your_$(echo $vars | tr 'A-Z' 'a-z')\" before first run" "$CRIT"
     fi
 done
 [ $missing = 1 ] && exit 1
 
-#check if curl and jq exists
+#check if curl (for the sake of...) and jq exists
 for app in curl jq; do
   if ! (which "$app" >/dev/null 2>&1); then
       Print_Output "$app not found, installing..." "$CRIT"
@@ -67,12 +74,12 @@ done
 
 if [ "$1" = "cron" ]; then
    if [ -z "$2" ] && [ -z "$RUNEACH" ]; then
-      Print_Output "Please use \"$(echo $APPNAME | tr 'A-Z' 'a-z') cron X\" where X is the number in minutes for cronjob" "$ERR"
+      Print_Output "Please use \"$APPNAMEnorm cron X\" where X is the number in minutes for cronjob" "$ERR"
       exit 1
    elif [ -n "$2" ]; then
       setvar RUNEACH "$2"
    fi
-   cru a "$APPNAME" "*/${RUNEACH} * * * * ${0}"
+   cru a "$APPNAME" "*/$RUNEACH * * * * $0"
    Print_Output "Creating cronjob to run every $RUNEACH minutes..." "$WARN"
    setvar CURRENTIP ""
    setvar CURRENTCOUNTRY ""
@@ -93,22 +100,23 @@ if [ -n "$2" ]; then
    NEWIP="$2"
    NEWCOUNTRY="$(echo "$3" | tr 'a-z' 'A-Z')"
 else
-    AIRVPN="$(curl -fs4 --retry 8 https://airvpn.org/api/whatismyip/)"
-   	NEWIP="$(jq -n "$AIRVPN" | jq -j .ip)"
-   	NEWCOUNTRY="$(jq -n "$AIRVPN" | jq -j .geo.code | tr 'a-z' 'A-Z')"
+   AIRVPN="$(curl -fs4 --retry 8 https://airvpn.org/api/whatismyip/)"
+   NEWIP="$(jq -n "$AIRVPN" | jq -j .ip)"
+   NEWCOUNTRY="$(jq -n "$AIRVPN" | jq -j .geo.code | tr 'a-z' 'A-Z')"
 fi
 
 [ -z "$NEWCOUNTRY" ] && NEWCOUNTRY="EARTH"
 
 if [ -z "$NEWIP" ] || [ "$NEWIP" = "null" ]; then
-    setvar CURRENTIP ""
-    setvar CURRENTCOUNTRY ""
-    Print_Output "Can't retrieve IP Address, stopping..." "$ERR"
+   setvar CURRENTIP ""
+   setvar CURRENTCOUNTRY ""
+   Print_Output "Can't retrieve IP Address, stopping..." "$ERR"
+   exit 1
 else
      if [ "$NEWIP" != "$CURRENTIP" ]; then
         UPDATE="$(curl -fs4 --retry 8 -u $USERNAME:$PASSWORD https://updates.dnsomatic.com/nic/update?hostname=$HOSTNAME\&wildcard=NOCHG\&mx=NOCHG\&backmx=NOCHG\&myip=$NEWIP)"
-		#if you need to curl another url to update another service, you can do it here, for example:
-		#curl -fs4 --retry 8 "https://link-ip.nextdns.io/confid/presharedkey" -o /dev/null #NextDNS linked IP
+	#if you need to curl another url to update another service, you can do it here, for example:
+	#curl -fs4 --retry 8 "https://link-ip.nextdns.io/confid/presharedkey" -o /dev/null #NextDNS linked IP
         if [ "$UPDATE" = "good $NEWIP" ] || [ "$UPDATE" = "nochg $NEWIP" ]; then
             if [ "$1" = "force" ]; then
                Print_Output "Forcing IP update to $NEWIP/$NEWCOUNTRY" "$PASS"
@@ -122,14 +130,15 @@ else
         elif [ "$UPDATE" = "abuse" ]; then
             setvar CURRENTIP ""
             setvar CURRENTCOUNTRY ""
-            Print_Output "Abusing! Nothing updated. Next update will be forced" "$ERR"
+	    setvar ABUSE 1
+            Print_Output "Abusing! Nothing updated. Next cron will be skipped and next update forced" "$ERR"
         else
             setvar CURRENTIP ""
             setvar CURRENTCOUNTRY ""
             Print_Output "Error while updating: \"$UPDATE\". Next update will be forced" "$ERR"
         fi
-   # else
-   #     Print_Output "Nothing to update. Current IP: $CURRENTIP/$CURRENTCOUNTRY" "$PASS"
+    else
+        [ $NOTH = 1 ] || Print_Output "Nothing to update. Current IP: $CURRENTIP/$CURRENTCOUNTRY" "$PASS"
     fi
 fi
 
